In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
a[0]

np.int64(1)

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.random.rand(2,3)

array([[0.07668149, 0.24884904, 0.81981615],
       [0.24166059, 0.10800865, 0.84952772]])

In [13]:
np.random.randn(3)

array([-0.52715167, -0.19442198, -0.55555198])

In [14]:
b.shape

(2, 3)

In [15]:
b.ndim

2

In [16]:
b.size

6

In [17]:
b.dtype

dtype('int64')

In [18]:
a[-1]

np.int64(3)

In [19]:
b[-1]

array([4, 5, 6])

In [20]:
b[0, 2]

np.int64(3)

In [21]:
b[1]

array([4, 5, 6])

In [22]:
b[:, 1]

array([2, 5])

In [23]:
b[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [24]:
b[0, 2] = 12

In [25]:
b[0, 2]

np.int64(12)

In [26]:
a=np.array([5, 12, 7, 20])

In [27]:
a>10

array([False,  True, False,  True])

In [28]:
a[a>10]

array([12, 20])

In [29]:
a[a>10]=0

In [30]:
a

array([5, 0, 7, 0])

In [31]:
a=np.array([1, 2, 3])

In [32]:
a*2

array([2, 4, 6])

In [33]:
a+a

array([2, 4, 6])

In [34]:
a+a+a

array([3, 6, 9])

In [35]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [40]:
m=np.array([[1, 2, 3], [4, 5, 6]])
v=np.array([10, 20, 30])

In [37]:
m+v

array([[11, 22, 33],
       [14, 25, 36]])

In [38]:
(m-m.mean(axis=0))/m.std(axis=0)

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [39]:
m.sum

In [41]:
m.sum()

np.int64(21)

In [42]:
m.mean()

np.float64(3.5)

In [43]:
m.sum(axis=0)

array([5, 7, 9])

In [44]:
m.sum(axis=1)

array([ 6, 15])

In [45]:
m.mean(axis=0)

array([2.5, 3.5, 4.5])

In [46]:
m.mean(axis=1)

array([2., 5.])

In [47]:
m.std(axis=0)

array([1.5, 1.5, 1.5])

In [48]:
m.std(axis=1)

array([0.81649658, 0.81649658])

In [49]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
m.min()

np.int64(1)

In [51]:
m.max()

np.int64(6)

In [52]:
m.argmax()

np.int64(5)

In [53]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
m.flatten

In [56]:
m.flatten()

array([1, 2, 3, 4, 5, 6])

In [57]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.random.rand(5,4)

array([[0.99785995, 0.65594377, 0.25760946, 0.85104709],
       [0.78938628, 0.96581871, 0.55214703, 0.07323717],
       [0.25475202, 0.91820841, 0.87029385, 0.95458939],
       [0.32788213, 0.35677769, 0.12307977, 0.96690903],
       [0.00963299, 0.6960619 , 0.36025836, 0.3060246 ]])

In [77]:
a = np.random.rand(5, 4)

In [78]:
a

array([[0.45276419, 0.32251029, 0.71290366, 0.37679488],
       [0.12143866, 0.14406196, 0.18533178, 0.57049907],
       [0.46345819, 0.10321167, 0.86026529, 0.8274395 ],
       [0.52620399, 0.73933835, 0.73675044, 0.2425018 ],
       [0.55613913, 0.16390798, 0.59384764, 0.94045267]])

In [79]:
a.mean(axis=0)

array([0.42400083, 0.29460605, 0.61781976, 0.59153758])

In [80]:
a.mean(axis=1)

array([0.46624326, 0.25533287, 0.56359366, 0.56119864, 0.56358686])

In [81]:
a.std(axis=0)

array([0.15609875, 0.23449639, 0.23220069, 0.26297319])

In [82]:
a.std(axis=1)

array([0.14973578, 0.18339763, 0.30806143, 0.20331287, 0.27511008])

In [84]:
(a-a.mean(axis=0))/a.std(axis=0)

array([[ 0.18426388,  0.11899647,  0.40949015, -0.81659545],
       [-1.93827417, -0.64198894, -1.86256113, -0.08000249],
       [ 0.25277177, -0.8161933 ,  1.04412061,  0.89705691],
       [ 0.65473398,  1.89654221,  0.51218916, -1.32726759],
       [ 0.84650454, -0.55735644, -0.10323879,  1.32680862]])

In [85]:
(a-a.mean(axis=1))/a.std(axis=1)

ValueError: operands could not be broadcast together with shapes (5,4) (5,)

In [86]:
(a-a.mean(axis=1))/a.std(axis=1)

ValueError: operands could not be broadcast together with shapes (5,4) (5,)

In [87]:
v=np.random.rand(4)

In [88]:
v

array([0.98128159, 0.19604279, 0.03168037, 0.38421559])

In [89]:
a+v

array([[1.43404579, 0.51855308, 0.74458403, 0.76101047],
       [1.10272025, 0.34010475, 0.21701215, 0.95471467],
       [1.44473978, 0.29925446, 0.89194566, 1.21165509],
       [1.50748558, 0.93538114, 0.76843081, 0.62671739],
       [1.53742072, 0.35995077, 0.62552802, 1.32466826]])

In [90]:
a_norm=(a-a.mean(axis=0))/a.std(axis=0)

In [91]:
a_norm.mean(axis=0)

array([ 1.33226763e-16,  1.33226763e-16, -3.19189120e-16,  8.88178420e-17])

In [92]:
a_norm.std(axis=0)

array([1., 1., 1., 1.])

In [93]:
import pandas as pd

In [94]:
df=pd.read_csv("titanic.csv")

In [95]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [96]:
df.shape

(891, 12)

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [98]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [100]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')